name: Build and Deploy Resume

on:
  push:
    branches:
      - main
    paths:
      - 'cv.typ'
      - '.github/workflows/deploy-resume.yml'
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst CLI
        uses: typst-community/setup-typst@v3

      - name: Install Source Sans 3 fonts
        run: |
          mkdir -p ~/.local/share/fonts/source-sans-3

          for font in Regular Italic Bold BoldItalic ExtraLight ExtraLightItalic Light LightItalic Medium MediumItalic SemiBold SemiBoldItalic; do
            wget -O ~/.local/share/fonts/source-sans-3/SourceSans3-$font.ttf \
              https://github.com/google/fonts/raw/main/ofl/sourcesans3/SourceSans3-$font.ttf
          done

          fc-cache -fv

      - name: Install required fonts
        run: |
          sudo apt update
          sudo apt install -y fonts-roboto fonts-font-awesome unzip wget

          mkdir -p ~/.local/share/fonts/source-sans-3
          for font in Regular Italic Bold BoldItalic ExtraLight ExtraLightItalic Light LightItalic Medium MediumItalic SemiBold SemiBoldItalic; do
          wget -q -O ~/.local/share/fonts/source-sans-3/SourceSans3-$font.ttf \
          https://github.com/google/fonts/raw/main/ofl/sourcesans3/SourceSans3-$font.ttf
          done
          
          fc-cache -fv

      - name: Compile resume
        run: typst compile cv.typ resume.pdf

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
